[2022-07-16 23:27:12,395] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: local_to_gcs.bash manual__2022-07-16T23:27:09.908208+00:00 [queued]>
[2022-07-16 23:27:12,427] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: local_to_gcs.bash manual__2022-07-16T23:27:09.908208+00:00 [queued]>
[2022-07-16 23:27:12,430] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 23:27:12,436] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-07-16 23:27:12,440] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 23:27:12,542] {taskinstance.py:1378} INFO - Executing <Task(BashOperator): bash> on 2022-07-16 23:27:09.908208+00:00
[2022-07-16 23:27:12,622] {standard_task_runner.py:52} INFO - Started process 5355 to run task
[2022-07-16 23:27:12,650] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'local_to_gcs', 'bash', 'manual__2022-07-16T23:27:09.908208+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/local_to_gcs.py', '--cfg-path', '/tmp/tmpiv3i5z9a', '--error-file', '/tmp/tmpuv2ax3_y']
[2022-07-16 23:27:12,656] {standard_task_runner.py:80} INFO - Job 24: Subtask bash
[2022-07-16 23:27:12,911] {task_command.py:370} INFO - Running <TaskInstance: local_to_gcs.bash manual__2022-07-16T23:27:09.908208+00:00 [running]> on host 32d1f26135d5
[2022-07-16 23:27:13,213] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=local_to_gcs
AIRFLOW_CTX_TASK_ID=bash
AIRFLOW_CTX_EXECUTION_DATE=2022-07-16T23:27:09.908208+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-16T23:27:09.908208+00:00
[2022-07-16 23:27:13,224] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-16 23:27:13,229] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mv /Users/giovanibaroni/data-engineering/final_project/***/country_partner_1999.csv > /opt/***/country_partner_1999.csv']
[2022-07-16 23:27:13,282] {subprocess.py:85} INFO - Output:
[2022-07-16 23:27:13,304] {subprocess.py:92} INFO - mv: missing destination file operand after '/Users/giovanibaroni/data-engineering/final_project/***/country_partner_1999.csv'
[2022-07-16 23:27:13,306] {subprocess.py:92} INFO - Try 'mv --help' for more information.
[2022-07-16 23:27:13,310] {subprocess.py:96} INFO - Command exited with return code 1
[2022-07-16 23:27:13,372] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-07-16 23:27:13,420] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=local_to_gcs, task_id=bash, execution_date=20220716T232709, start_date=20220716T232712, end_date=20220716T232713
[2022-07-16 23:27:13,484] {standard_task_runner.py:97} ERROR - Failed to execute job 24 for task bash (Bash command failed. The command returned a non-zero exit code 1.; 5355)
[2022-07-16 23:27:13,571] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 23:27:13,956] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
