[2022-07-20 00:01:05,897] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: gcs_to_bq.bq_country_product_trade_external_table_task manual__2022-07-19T23:42:49.341835+00:00 [queued]>
[2022-07-20 00:01:05,919] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: gcs_to_bq.bq_country_product_trade_external_table_task manual__2022-07-19T23:42:49.341835+00:00 [queued]>
[2022-07-20 00:01:05,923] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 00:01:05,925] {taskinstance.py:1358} INFO - Starting attempt 3 of 4
[2022-07-20 00:01:05,928] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 00:01:05,958] {taskinstance.py:1378} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bq_country_product_trade_external_table_task> on 2022-07-19 23:42:49.341835+00:00
[2022-07-20 00:01:05,996] {standard_task_runner.py:52} INFO - Started process 74769 to run task
[2022-07-20 00:01:06,007] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bq', 'bq_country_product_trade_external_table_task', 'manual__2022-07-19T23:42:49.341835+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag.py', '--cfg-path', '/tmp/tmppt54yaun', '--error-file', '/tmp/tmp9f7rwqz8']
[2022-07-20 00:01:06,011] {standard_task_runner.py:80} INFO - Job 93: Subtask bq_country_product_trade_external_table_task
[2022-07-20 00:01:06,117] {task_command.py:370} INFO - Running <TaskInstance: gcs_to_bq.bq_country_product_trade_external_table_task manual__2022-07-19T23:42:49.341835+00:00 [running]> on host 32d1f26135d5
[2022-07-20 00:01:06,246] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_to_bq
AIRFLOW_CTX_TASK_ID=bq_country_product_trade_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T23:42:49.341835+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-19T23:42:49.341835+00:00
[2022-07-20 00:01:06,256] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-07-20 00:01:06,260] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-07-20 00:01:07,587] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1108, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 400, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/united-electron-351323/datasets/international_economics_data_lake/tables?prettyPrint=false: Error while reading table: country_product_trade_external_table, error message: Failed to expand table country_product_trade_external_table with file pattern gs://dtc_data_lake_united-electron-351323/international_economics/data_lake/country_product_trade/*: matched no files. File: gs://dtc_data_lake_united-electron-351323/international_economics/data_lake/country_product_trade/*
[2022-07-20 00:01:08,135] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_to_bq, task_id=bq_country_product_trade_external_table_task, execution_date=20220719T234249, start_date=20220720T000105, end_date=20220720T000108
[2022-07-20 00:01:08,290] {standard_task_runner.py:97} ERROR - Failed to execute job 93 for task bq_country_product_trade_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/united-electron-351323/datasets/international_economics_data_lake/tables?prettyPrint=false: Error while reading table: country_product_trade_external_table, error message: Failed to expand table country_product_trade_external_table with file pattern gs://dtc_data_lake_united-electron-351323/international_economics/data_lake/country_product_trade/*: matched no files. File: gs://dtc_data_lake_united-electron-351323/international_economics/data_lake/country_product_trade/*; 74769)
[2022-07-20 00:01:08,417] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-20 00:01:08,615] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
