[2022-06-01 11:18:29,913] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_yellow_tripdata_external_table_task scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-06-01 11:18:29,925] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_yellow_tripdata_external_table_task scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-06-01 11:18:29,926] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 11:18:29,928] {taskinstance.py:1358} INFO - Starting attempt 2 of 2
[2022-06-01 11:18:29,930] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 11:18:29,949] {taskinstance.py:1378} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bq_yellow_tripdata_external_table_task> on 2022-05-31 00:00:00+00:00
[2022-06-01 11:18:29,964] {standard_task_runner.py:52} INFO - Started process 1126 to run task
[2022-06-01 11:18:29,973] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_yellow_tripdata_external_table_task', 'scheduled__2022-05-31T00:00:00+00:00', '--job-id', '496', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag.py', '--cfg-path', '/tmp/tmpiq3d9w3e', '--error-file', '/tmp/tmp1v1fqjc0']
[2022-06-01 11:18:29,979] {standard_task_runner.py:80} INFO - Job 496: Subtask bq_yellow_tripdata_external_table_task
[2022-06-01 11:18:30,059] {task_command.py:370} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_yellow_tripdata_external_table_task scheduled__2022-05-31T00:00:00+00:00 [running]> on host 80b81dda36ea
[2022-06-01 11:18:30,162] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_yellow_tripdata_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-05-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-31T00:00:00+00:00
[2022-06-01 11:18:30,165] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-06-01 11:18:30,167] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-06-01 11:18:31,005] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1108, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 400, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/united-electron-351323/datasets/trips_data_all/tables?prettyPrint=false: Error while reading table: yellow_tripdata_external_table, error message: Failed to expand table yellow_tripdata_external_table with file pattern gs://dtc_data_lake_united-electron-351323/yellow/*: matched no files.
[2022-06-01 11:18:31,030] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=gcs_2_bq_dag, task_id=bq_yellow_tripdata_external_table_task, execution_date=20220531T000000, start_date=20220601T111829, end_date=20220601T111831
[2022-06-01 11:18:31,048] {standard_task_runner.py:97} ERROR - Failed to execute job 496 for task bq_yellow_tripdata_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/united-electron-351323/datasets/trips_data_all/tables?prettyPrint=false: Error while reading table: yellow_tripdata_external_table, error message: Failed to expand table yellow_tripdata_external_table with file pattern gs://dtc_data_lake_united-electron-351323/yellow/*: matched no files.; 1126)
[2022-06-01 11:18:31,105] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-01 11:18:31,171] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
