[2022-07-16 23:24:54,355] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: local_to_gcs.download_dataset_task manual__2022-07-16T23:24:52.675859+00:00 [queued]>
[2022-07-16 23:24:54,397] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: local_to_gcs.download_dataset_task manual__2022-07-16T23:24:52.675859+00:00 [queued]>
[2022-07-16 23:24:54,401] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 23:24:54,403] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-07-16 23:24:54,405] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 23:24:54,435] {taskinstance.py:1378} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-16 23:24:52.675859+00:00
[2022-07-16 23:24:54,450] {standard_task_runner.py:52} INFO - Started process 5232 to run task
[2022-07-16 23:24:54,462] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'local_to_gcs', 'download_dataset_task', 'manual__2022-07-16T23:24:52.675859+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/local_to_gcs.py', '--cfg-path', '/tmp/tmpgdqkjvkj', '--error-file', '/tmp/tmpz54rqdna']
[2022-07-16 23:24:54,468] {standard_task_runner.py:80} INFO - Job 22: Subtask download_dataset_task
[2022-07-16 23:24:54,564] {task_command.py:370} INFO - Running <TaskInstance: local_to_gcs.download_dataset_task manual__2022-07-16T23:24:52.675859+00:00 [running]> on host 32d1f26135d5
[2022-07-16 23:24:54,834] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=local_to_gcs
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-16T23:24:52.675859+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-16T23:24:52.675859+00:00
[2022-07-16 23:24:54,868] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-16 23:24:54,876] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mv /Users/giovanibaroni/data-engineering/final_project/***/country_partner_1999.csv > /opt/***/country_partner_1999.csv']
[2022-07-16 23:24:54,966] {subprocess.py:85} INFO - Output:
[2022-07-16 23:24:55,033] {subprocess.py:92} INFO - mv: missing destination file operand after '/Users/giovanibaroni/data-engineering/final_project/***/country_partner_1999.csv'
[2022-07-16 23:24:55,040] {subprocess.py:92} INFO - Try 'mv --help' for more information.
[2022-07-16 23:24:55,044] {subprocess.py:96} INFO - Command exited with return code 1
[2022-07-16 23:24:55,098] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-07-16 23:24:55,121] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=local_to_gcs, task_id=download_dataset_task, execution_date=20220716T232452, start_date=20220716T232454, end_date=20220716T232455
[2022-07-16 23:24:55,307] {standard_task_runner.py:97} ERROR - Failed to execute job 22 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 5232)
[2022-07-16 23:24:55,400] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 23:24:55,624] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
